assets: /data/syh/nora/LIBERO/libero/libero/./assets
bddl_files: /data/syh/nora/LIBERO/libero/libero/./bddl_files
benchmark_root: /data/syh/nora/LIBERO/libero/libero
datasets: /data/syh/nora/LIBERO/libero/libero/../datasets
init_states: /data/syh/nora/LIBERO/libero/libero/./init_files
